## Find idea K for Knn

In [1]:
import sklearn
import pandas as pd
import numpy as np
from App import App

In [2]:
# load instance with real data
app = App()
app.configure()

In [4]:
def test_dataset(app, dataMat, K, simMeas):
    total_errors = 0.0
    total_count = 0
    number_of_items = np.shape(dataMat)[1]
    for user in range(len(dataMat)):
        for item in range(number_of_items):
            rating = dataMat[user, item]
            if rating == 0:
                continue
            # user id is 1 based, but dataset has extra record of user_id = 0
            # movie id is 1-based
            estimatedRating = app.bs_recommend.recommend_rating(user, item + 1, K)
            total_errors += abs(estimatedRating - rating)
            total_count += 1
    MAE = total_errors / total_count
    print('Mean Absoloute Error for K=', K, 'simMeas=', simMeas, ' : ', MAE)
    return MAE

In [5]:
def find_ideal_K(app, dataMat, simMeas):
    maes = []
    for k in range(1,21):
        maes.append(test_dataset(app, dataMat, k, simMeas))
    plt.figure(figsize=(10,2))
    plt.plot(range(1,21),maes,color='blue', linestyle='dashed', 
             marker='o',markerfacecolor='red', markersize=10)
    plt.title('MAE vs. K Value')
    plt.xlabel('K')
    plt.ylabel('MAE')
    print("Minimum MAE:",min(maes),"at K =",maes.index(min(maes)) + 1)

In [10]:
df_ratmat = pd.read_csv(
            "movielens/Movielens-02/data_matrix.csv", index_col=0)
ratmat = np.mat(df_ratmat)

In [12]:
find_ideal_K(app, ratmat, "n/a")

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75


KeyboardInterrupt: 

In [11]:
len(df_ratmat)

944

In [23]:
ratmat.sum(0)[:,100:110]

matrix([[238, 169,  28,   7, 190, 205, 147, 200, 446,  78]])

In [3]:
app.bs_recommend.recommend_rating(944, 266, 7)

     1    2    3    4    5    6    7    8    9   10  ...  1673  1674  1675  \
0  4.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  ...   0.0   0.0   0.0   

   1676  1677  1678  1679  1680  1681  1682  
0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[1 rows x 1682 columns]
0 index: 21 user_id: 545 rating: 2 score: 0.409003364689843
1 index: 6 user_id: 137 rating: 5 score: 0.4078907653319299
2 index: 15 user_id: 479 rating: 3 score: 0.40081602758207935
3 index: 9 user_id: 230 rating: 4 score: 0.3990257375685027
4 index: 25 user_id: 660 rating: 2 score: 0.3795310556400706
5 index: 31 user_id: 831 rating: 3 score: 0.3631393547904319
6 index: 0 user_id: 1 rating: 1 score: 0.34641493094394993
expected rating ===> 2.9014875741290163


2.9014875741290163

In [4]:
app.knn_n_neighbor

10

In [5]:
app.bs_recommend.recommend_rating(4, 1, 10)

[[0 0 0 ... 0 0 0]]
0 index: 390 user_id: 817 rating: 4 score: 0.289102996424486
1 index: 263 user_id: 550 rating: 3 score: 0.27078441134364106
2 index: 275 user_id: 580 rating: 3 score: 0.25307086369525844
3 index: 153 user_id: 324 rating: 5 score: 0.22964688215997575
4 index: 136 user_id: 294 rating: 5 score: 0.21576864040858545
5 index: 397 user_id: 831 rating: 4 score: 0.21261172988812727
6 index: 346 user_id: 730 rating: 4 score: 0.20679313348248085
7 index: 31 user_id: 66 rating: 3 score: 0.205779128967424
8 index: 342 user_id: 721 rating: 5 score: 0.2016646503060242
9 index: 120 user_id: 265 rating: 5 score: 0.2002217484533272
expected rating ===> 4.051485622833065


4.051485622833065

In [6]:
app.bs_recommend.recommend_rating(3, 1, 10)

[[0 0 0 ... 0 0 0]]
0 index: 136 user_id: 294 rating: 5 score: 0.30224657222291607
1 index: 22 user_id: 54 rating: 4 score: 0.26423072677213455
2 index: 397 user_id: 831 rating: 4 score: 0.23771433176811718
3 index: 298 user_id: 635 rating: 4 score: 0.23749177615316108
4 index: 294 user_id: 624 rating: 4 score: 0.23606414973887402
5 index: 153 user_id: 324 rating: 5 score: 0.23549394523807798
6 index: 423 user_id: 894 rating: 4 score: 0.23487352268210682
7 index: 437 user_id: 919 rating: 4 score: 0.2242006999787286
8 index: 250 user_id: 526 rating: 5 score: 0.20973185515755755
9 index: 342 user_id: 721 rating: 5 score: 0.20603688746913207
expected rating ===> 4.399277861897961


4.399277861897961

In [7]:
app.bs_recommend.recommend_rating(294, 1, 10)

[[5 0 0 ... 0 0 0]]
0 index: 14 user_id: 26 rating: 3 score: 0.5426445000762526
1 index: 293 user_id: 624 rating: 4 score: 0.5313629127895768
2 index: 22 user_id: 54 rating: 4 score: 0.529469768715587
3 index: 449 user_id: 938 rating: 4 score: 0.49001110249999114
4 index: 204 user_id: 432 rating: 2 score: 0.4810694083658399
5 index: 67 user_id: 141 rating: 3 score: 0.4734906941547976
6 index: 275 user_id: 582 rating: 4 score: 0.45709171649125613
7 index: 345 user_id: 730 rating: 4 score: 0.4568265608481732
8 index: 439 user_id: 923 rating: 3 score: 0.45373605769988223
9 index: 249 user_id: 526 rating: 5 score: 0.4469318782514028
expected rating ===> 3.591768998958921


3.591768998958921

In [10]:
app.bs_recommend.recommend_rating(294, 1, 10)

idx: [136]
[[5 0 0 ... 0 0 0]]
0 index: 14 user_id: 26 rating: 3 score: 0.5426445000762526
1 index: 293 user_id: 624 rating: 4 score: 0.5313629127895768
2 index: 22 user_id: 54 rating: 4 score: 0.529469768715587
3 index: 449 user_id: 938 rating: 4 score: 0.49001110249999114
4 index: 204 user_id: 432 rating: 2 score: 0.4810694083658399
5 index: 67 user_id: 141 rating: 3 score: 0.4734906941547976
6 index: 275 user_id: 582 rating: 4 score: 0.45709171649125613
7 index: 345 user_id: 730 rating: 4 score: 0.4568265608481732
8 index: 439 user_id: 923 rating: 3 score: 0.45373605769988223
9 index: 249 user_id: 526 rating: 5 score: 0.4469318782514028
expected rating ===> 3.591768998958921


3.591768998958921

In [13]:
app.bs_recommend.__dir__()

['recommend_service',
 '__module__',
 '__init__',
 'recommend_rating',
 'recommend_movie_by_genre',
 '__dict__',
 '__weakref__',
 '__doc__',
 '__repr__',
 '__hash__',
 '__str__',
 '__getattribute__',
 '__setattr__',
 '__delattr__',
 '__lt__',
 '__le__',
 '__eq__',
 '__ne__',
 '__gt__',
 '__ge__',
 '__new__',
 '__reduce_ex__',
 '__reduce__',
 '__subclasshook__',
 '__init_subclass__',
 '__format__',
 '__sizeof__',
 '__dir__',
 '__class__']

In [12]:
dd = df_ratmat[df_ratmat.iloc[:, 1 - 1] > 0]
dd[64:]

1  2  3  4  5  6  7  8  9  10  ...  1673  1674  1675  1676  1677  \
user_id                                 ...                                 
134      5  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0   
137      3  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0   
138      4  0  0  0  0  0  0  0  0   0  ...     0     0     0     0     0   
141      3  0  0  0  0  0  5  0  0   0  ...     0     0     0     0     0   
144      4  0  0  4  0  0  2  4  5   0  ...     0     0     0     0     0   
...     .. .. .. .. .. .. .. .. ..  ..  ...   ...   ...   ...   ...   ...   
934      2  4  0  5  0  0  0  0  0   0  ...     0     0     0     0     0   
935      3  0  0  0  0  0  0  0  1   0  ...     0     0     0     0     0   
936      4  0  4  0  0  5  4  0  4   0  ...     0     0     0     0     0   
938      4  0  0  0  0  0  4  0  3   0  ...     0     0     0     0     0   
941      5  0  0  0  0  0  4  0  0   0  ...     0     0     0     0     0   

         1678  1679  1680  1681  1682  
user_id                                
134         0     0     0     0     0  
137         0     0     0     0     0  
138         0     0     0     0     0  
141         0     0     0     0     0  
144         0     0     0     0     0  
...       ...   ...   ...   ...   ...  
934         0     0     0     0     0  
935         0     0     0     0     0  
936         0     0     0     0     0  
938         0     0     0     0     0  
941         0     0     0     0     0  

[388 rows x 1682 columns]

In [13]:
t = np.nonzero(dd.index == 294)[0]

In [17]:
937 in dd.index

False

In [18]:
dd.loc[935]

1       3
2       0
3       0
4       0
5       0
       ..
1678    0
1679    0
1680    0
1681    0
1682    0
Name: 935, Length: 1682, dtype: int64

In [19]:
np.array([dd.loc[935]])

array([[3, 0, 0, ..., 0, 0, 0]])

In [10]:
len(dd)

NameError: name 'dd' is not defined

In [13]:
t

array([136])

In [14]:
dd.loc[294]

1       5
2       0
3       0
4       0
5       0
       ..
1678    0
1679    0
1680    0
1681    0
1682    0
Name: 294, Length: 1682, dtype: int64

In [15]:
dd

1  2  3  4  5  6  7  8  9  10  ...  1673  1674  1675  1676  1677  \
user_id                                 ...                                 
1        5  3  4  3  3  5  4  1  5   3  ...     0     0     0     0     0   
2        4  0  0  0  0  0  0  0  0   2  ...     0     0     0     0     0   
5        4  3  0  0  0  0  0  0  0   0  ...     0     0     0     0     0   
6        4  0  0  0  0  0  2  4  4   0  ...     0     0     0     0     0   
10       4  0  0  4  0  0  4  0  4   0  ...     0     0     0     0     0   
...     .. .. .. .. .. .. .. .. ..  ..  ...   ...   ...   ...   ...   ...   
934      2  4  0  5  0  0  0  0  0   0  ...     0     0     0     0     0   
935      3  0  0  0  0  0  0  0  1   0  ...     0     0     0     0     0   
936      4  0  4  0  0  5  4  0  4   0  ...     0     0     0     0     0   
938      4  0  0  0  0  0  4  0  3   0  ...     0     0     0     0     0   
941      5  0  0  0  0  0  4  0  0   0  ...     0     0     0     0     0   

         1678  1679  1680  1681  1682  
user_id                                
1           0     0     0     0     0  
2           0     0     0     0     0  
5           0     0     0     0     0  
6           0     0     0     0     0  
10          0     0     0     0     0  
...       ...   ...   ...   ...   ...  
934         0     0     0     0     0  
935         0     0     0     0     0  
936         0     0     0     0     0  
938         0     0     0     0     0  
941         0     0     0     0     0  

[452 rows x 1682 columns]

In [16]:
dd.drop([5])

1  2  3  4  5  6  7  8  9  10  ...  1673  1674  1675  1676  1677  \
user_id                                 ...                                 
1        5  3  4  3  3  5  4  1  5   3  ...     0     0     0     0     0   
2        4  0  0  0  0  0  0  0  0   2  ...     0     0     0     0     0   
6        4  0  0  0  0  0  2  4  4   0  ...     0     0     0     0     0   
10       4  0  0  4  0  0  4  0  4   0  ...     0     0     0     0     0   
13       3  3  0  5  1  0  2  4  3   0  ...     0     0     0     0     0   
...     .. .. .. .. .. .. .. .. ..  ..  ...   ...   ...   ...   ...   ...   
934      2  4  0  5  0  0  0  0  0   0  ...     0     0     0     0     0   
935      3  0  0  0  0  0  0  0  1   0  ...     0     0     0     0     0   
936      4  0  4  0  0  5  4  0  4   0  ...     0     0     0     0     0   
938      4  0  0  0  0  0  4  0  3   0  ...     0     0     0     0     0   
941      5  0  0  0  0  0  4  0  0   0  ...     0     0     0     0     0   

         1678  1679  1680  1681  1682  
user_id                                
1           0     0     0     0     0  
2           0     0     0     0     0  
6           0     0     0     0     0  
10          0     0     0     0     0  
13          0     0     0     0     0  
...       ...   ...   ...   ...   ...  
934         0     0     0     0     0  
935         0     0     0     0     0  
936         0     0     0     0     0  
938         0     0     0     0     0  
941         0     0     0     0     0  

[451 rows x 1682 columns]

In [37]:
dd.loc[5][8] = 1

In [38]:
dd

1  2  3  4  5  6  7  8  9  10  ...  1673  1674  1675  1676  1677  \
user_id                                 ...                                 
1        5  3  4  3  3  5  4  1  5   3  ...     0     0     0     0     0   
2        4  0  0  0  0  0  0  0  0   2  ...     0     0     0     0     0   
5        1  3  0  0  0  0  0  0  1   1  ...     0     0     0     0     0   
6        1  0  0  0  0  0  2  4  4   0  ...     0     0     0     0     0   
10       4  0  0  4  0  0  4  0  4   0  ...     0     0     0     0     0   
...     .. .. .. .. .. .. .. .. ..  ..  ...   ...   ...   ...   ...   ...   
934      2  4  0  5  0  0  0  0  0   0  ...     0     0     0     0     0   
935      3  0  0  0  0  0  0  0  1   0  ...     0     0     0     0     0   
936      4  0  4  0  0  5  4  0  4   0  ...     0     0     0     0     0   
938      4  0  0  0  0  0  4  0  3   0  ...     0     0     0     0     0   
941      5  0  0  0  0  0  4  0  0   0  ...     0     0     0     0     0   

         1678  1679  1680  1681  1682  
user_id                                
1           0     0     0     0     0  
2           0     0     0     0     0  
5           0     0     0     0     0  
6           0     0     0     0     0  
10          0     0     0     0     0  
...       ...   ...   ...   ...   ...  
934         0     0     0     0     0  
935         0     0     0     0     0  
936         0     0     0     0     0  
938         0     0     0     0     0  
941         0     0     0     0     0  

[452 rows x 1682 columns]

In [18]:
dd.index == 15

array([False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False,

In [ ]:
ratmat = np.array(df_ratmat)

In [ ]:
app.bs_recommend.recommend_movie_by_genre("Toy Story (1995)", 10)

In [8]:
app.bs_recommend.recommend_rating(3, 0, 3)

KeyError: 3

In [4]:
app.bs_recommend.recommend_rating(3, 0, 3)

KeyError: 3

In [10]:
sorted(sklearn.neighbors.VALID_METRICS['brute'])

['braycurtis',
 'canberra',
 'chebyshev',
 'cityblock',
 'correlation',
 'cosine',
 'cosine',
 'dice',
 'euclidean',
 'hamming',
 'haversine',
 'jaccard',
 'kulsinski',
 'l1',
 'l2',
 'mahalanobis',
 'manhattan',
 'matching',
 'minkowski',
 'nan_euclidean',
 'precomputed',
 'rogerstanimoto',
 'russellrao',
 'seuclidean',
 'sokalmichener',
 'sokalsneath',
 'sqeuclidean',
 'wminkowski',
 'yule']

In [6]:
import contextlib
with contextlib.ExitStack() as patches:
    mock_knn = patches.enter_context(mock.patch('App.Knn'))
    mock_genre = patches.enter_context(mock.patch('App.Genre'))
    mock_bs = patches.enter_context(mock.patch('App.bs'))
    mock_ms = patches.enter_context(mock.patch('App.ms'))
    mock_us = patches.enter_context(mock.patch('App.us'))
    mock_cs = patches.enter_context(mock.patch('App.cs'))
    mock_rs = patches.enter_context(mock.patch('App.rs'))
    mock_md = patches.enter_context(mock.patch('App.md'))
    mock_ud = patches.enter_context(mock.patch('App.ud'))
    mock_rd = patches.enter_context(mock.patch('App.rd'))
    mock_ui = patches.enter_context(mock.patch('App.UI'))
    app = App()
    app.configure()
    mock_bs.MovieService.assert_called_once()
    mock_bs.UserService.assert_called_once()
    mock_bs.RatingService.assert_called_once()
    mock_bs.RecommendService.assert_called_once()
    mock_ms.MovieService.assert_called_once()
    mock_us.UserService.assert_called_once()
    mock_cs.RecommendService.assert_called_once()
    mock_rs.RatingService.assert_called_once()
    mock_md.MovieData.assert_called_once()
    mock_ud.UserData.assert_called_once()
    mock_rd.RatingData.assert_called_once()
    mock_ui.assert_called_once()
    mock_knn.assert_called_once_with('pearson', 10)
    mock_genre.assert_called_once()
    print("All Passed")

All Passed


In [25]:
app.bs_movie.get_movie_by_title("unknown").get_title()

'unknown'